@startuml service_auto

entity Angajati
{
  *id: number
  --
  +mail: varchar
  #nume: varchar2
  #prenume: varchar2
  #numar_telefon: varchar2
  gender: ??
  zi_de_nastere: date
  #job_id: number
  #id_departament: number
  #id_adresa: number
  #data_angajarii: date
  --
  --
  CONSTRAINT mail
  CONSTRAINT gender
  CONSTRAINT numar_telefon
}

entity Joburi
{
  *id: number
  --
  nume_job: varchar2
}

entity Departamente
{
  *id: number
  --
  #nume_departament: varchar2
}

entity Sarcini
{
  *id: number
  --
  #titlu: varchar2
  descriere: TEXT
  id_departament: number
  id_angajat: number
  #progres: index
  #creat_la: date
  inceput_la: date
  sfarsit_la: date
  info_progres: TEXT
  --
  --
  CONSTRAINT progres
  CONSTRAINT sfarsit_la
  CONSTRAINT inceput_la
  CONSTRAINT info_progres
}

entity Pontaj_Angajati
{
  *id: number
  --
  #id_angajat: number
  #clock_in: date
  clock_out: date
  id_sarcina: number
  timp: date/timestamp
  --
  --
  CONSTRAINT clock_out_valid CHECK (clock_out IS NULL or clock_out > clock_in)
}

entity Adrese_Angajati
{
  +id: number
  --
  #judet: varchar2
  #oras: varchar2
  #strada: varchar2
  #numar: number
  bloc: number
  scara: varchar2
}

entity Istoric_Angajati
{
  +id: number
  --
  #id_angajat: number
  #id_departament: number
  #id_job: number
  #data_start: date
  data_sfarsit: date
  --
  --
  CONSTRAINT data_sfarsit_valid CHECK (data_sfarsit IS NULL or data_sfarsit > data_start)
}

Angajati }o--|| Joburi: "fk (id job)"
Angajati }o--|| Adrese_Angajati: "fk (id adresa)"
Angajati }o--|| Departamente: "fk (id departament)"
Angajati ||--o{ Pontaj_Angajati: "fk (id angajat)"
Angajati ||--o{ Sarcini: "fk (id angajat)"
Sarcini  }o--o{ Departamente: "fk (id departament)"
Sarcini  }o--|| Pontaj_Angajati: "fk (id sarcina)"
Istoric_Angajati --o{ Joburi: "fk (id job)"
Istoric_Angajati --o{ Departamente: "fk (id departament)"
Istoric_Angajati }o--o{ Angajati: "fk (id angajat)"

legend
  E ➡️ Entitate (tabel)

  fk ➡️ foreign key (cheie externa)
endlegend

@enduml
